services:
  trackerservice:
    image: trackerservice
    build:
      context: /src
      dockerfile: TrackerService/Dockerfile
      
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres